=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::BrandsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BrandsApi' do
  before do
    # run before each test
    @api_instance = Solifyn::BrandsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BrandsApi' do
    it 'should create an instance of BrandsApi' do
      expect(@api_instance).to be_instance_of(Solifyn::BrandsApi)
    end
  end

  # unit tests for brands_create
  # Create Brand
  # Add a new brand identity under the current active business.
  # @param brand_create 
  # @param [Hash] opts the optional parameters
  # @return [Brand]
  describe 'brands_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for brands_get
  # Retrieve Brand
  # Retrieve details of a brand identity by ID.
  # @param id The brand ID to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Brand]
  describe 'brands_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for brands_list
  # List Brands
  # Retrieve all brands associated with the current business context.
  # @param [Hash] opts the optional parameters
  # @return [Array<Brand>]
  describe 'brands_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for brands_update
  # Update Brand
  # Update website, logo, description, or statement descriptors of a brand.
  # @param id The brand ID to update
  # @param brand_update 
  # @param [Hash] opts the optional parameters
  # @return [Brand]
  describe 'brands_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
