=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::BusinessesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BusinessesApi' do
  before do
    # run before each test
    @api_instance = Solifyn::BusinessesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BusinessesApi' do
    it 'should create an instance of BusinessesApi' do
      expect(@api_instance).to be_instance_of(Solifyn::BusinessesApi)
    end
  end

  # unit tests for businesses_billing_history
  # Get Platform Billing History
  # Retrieve history of SaaS subscription payments paid by this business to the platform.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'businesses_billing_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchants_generate_api_keys
  # Rotate Whop API Keys
  # Generate and sync a new Whop Child Company API key (restricted to business owners).
  # @param [Hash] opts the optional parameters
  # @return [WhopApiKeysRotation]
  describe 'merchants_generate_api_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchants_update_page
  # Update Page configuration
  # Modify store page content configs, banner images, or avatar details.
  # @param user_theme_update 
  # @param [Hash] opts the optional parameters
  # @return [UserPage]
  describe 'merchants_update_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchants_update_settings
  # Update Merchant Settings
  # Update profile parameters, SEO, Google analytics, and email notification properties.
  # @param user_settings_update 
  # @param [Hash] opts the optional parameters
  # @return [UserSettings]
  describe 'merchants_update_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchants_update_theme
  # Update Theme
  # Update colors, fonts, avatar, or banner settings for the store.
  # @param user_theme_update 
  # @param [Hash] opts the optional parameters
  # @return [UserTheme]
  describe 'merchants_update_theme test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
