=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::ChatApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChatApi' do
  before do
    # run before each test
    @api_instance = Solifyn::ChatApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChatApi' do
    it 'should create an instance of ChatApi' do
      expect(@api_instance).to be_instance_of(Solifyn::ChatApi)
    end
  end

  # unit tests for chat_controller_get_merchant_messages
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chat_controller_get_merchant_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for chat_controller_get_merchant_sessions
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chat_controller_get_merchant_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for chat_controller_send_customer_message
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chat_controller_send_customer_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for chat_controller_send_merchant_message
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chat_controller_send_merchant_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
