=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::CollectionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CollectionsApi' do
  before do
    # run before each test
    @api_instance = Solifyn::CollectionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CollectionsApi' do
    it 'should create an instance of CollectionsApi' do
      expect(@api_instance).to be_instance_of(Solifyn::CollectionsApi)
    end
  end

  # unit tests for collections_add_products
  # Add Products to Collection
  # Add one or more products to a collection. If a product already exists, its quantity is updated.
  # @param id Collection ID
  # @param add_collection_products_dto 
  # @param [Hash] opts the optional parameters
  # @return [CollectionResponseDto]
  describe 'collections_add_products test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_archive
  # Archive Collection
  # Deactivate and move a collection to archives.
  # @param id Collection ID
  # @param [Hash] opts the optional parameters
  # @return [CollectionArchivedResponseDto]
  describe 'collections_archive test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_create
  # Create Collection
  # Generate a new product collection for checkout packaging.
  # @param create_collection_dto 
  # @param [Hash] opts the optional parameters
  # @return [CollectionResponseDto]
  describe 'collections_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_delete_product
  # Remove Product from Collection
  # Remove a product from a collection.
  # @param id Collection ID
  # @param product_id Product ID
  # @param [Hash] opts the optional parameters
  # @return [CollectionProductDeletedResponseDto]
  describe 'collections_delete_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_get
  # Retrieve Collection
  # Get properties of a product collection by ID.
  # @param id Collection ID
  # @param [Hash] opts the optional parameters
  # @return [CollectionDetailResponseDto]
  describe 'collections_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_list
  # List Collections
  # Get all active product collections linked to the current active business.
  # @param [Hash] opts the optional parameters
  # @return [Array<CollectionResponseDto>]
  describe 'collections_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_list_archived
  # List Archived Collections
  # Get all archived/deactivated product collections.
  # @param [Hash] opts the optional parameters
  # @return [Array<CollectionResponseDto>]
  describe 'collections_list_archived test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_unarchive
  # Unarchive Collection
  # Restore an archived collection back to active status.
  # @param id Collection ID
  # @param [Hash] opts the optional parameters
  # @return [CollectionUnarchivedResponseDto]
  describe 'collections_unarchive test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_update
  # Update Collection
  # Update products, friendly name, status, or description of a collection.
  # @param id Collection ID
  # @param update_collection_dto 
  # @param [Hash] opts the optional parameters
  # @return [CollectionUpdatedResponseDto]
  describe 'collections_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for collections_update_product
  # Update Collection Product
  # Update quantity of a specific product inside a collection.
  # @param id Collection ID
  # @param product_id Product ID
  # @param update_collection_product_dto 
  # @param [Hash] opts the optional parameters
  # @return [CollectionProductUpdatedResponseDto]
  describe 'collections_update_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
