=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = Solifyn::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(Solifyn::DefaultApi)
    end
  end

  # unit tests for dispute_created_post
  # Dispute Created
  # Occurs when a payment charge is disputed by the customer (chargeback initiated).
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'dispute_created_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for dispute_lost_post
  # Dispute Lost
  # Occurs when a dispute challenge is lost and the funds are returned to the cardholder.
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'dispute_lost_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for dispute_won_post
  # Dispute Won
  # Occurs when a dispute challenge is won by the merchant.
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'dispute_won_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for license_created_post
  # License Created
  # Occurs when a new software license key is created or assigned to a customer purchase.
  # @param [Hash] opts the optional parameters
  # @option opts [License] :license 
  # @return [nil]
  describe 'license_created_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for license_revoked_post
  # License Revoked
  # Occurs when a software license key is revoked (e.g., due to subscription cancellation, refund, or dispute).
  # @param [Hash] opts the optional parameters
  # @option opts [License] :license 
  # @return [nil]
  describe 'license_revoked_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payment_created_post
  # Payment Created
  # Occurs when a new payment is initiated (e.g., at checkout start or subscription creation). The payment may still be in an incomplete or pending state.
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'payment_created_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payment_failed_post
  # Payment Failed
  # Occurs when a customer payment attempt fails.
  # @param [Hash] opts the optional parameters
  # @option opts [Order] :order 
  # @return [nil]
  describe 'payment_failed_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payment_succeeded_post
  # Payment Succeeded
  # Occurs when a customer payment is confirmed as succeeded.
  # @param [Hash] opts the optional parameters
  # @option opts [Order] :order 
  # @return [nil]
  describe 'payment_succeeded_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for refund_failed_post
  # Refund Failed
  # Occurs when a payment refund fails.
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'refund_failed_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for refund_succeeded_post
  # Refund Succeeded
  # Occurs when a payment refund is confirmed as succeeded.
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'refund_succeeded_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscription_created_post
  # Subscription Created
  # Occurs when a customer subscription is successfully started.
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'subscription_created_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscription_deactivated_post
  # Subscription Deactivated
  # Occurs when a customer subscription is deactivated or expired.
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'subscription_deactivated_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscription_updated_post
  # Subscription Updated
  # Occurs when a customer subscription is updated (e.g., cancel at period end changes).
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [nil]
  describe 'subscription_updated_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
