=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::DigitalFileApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DigitalFileApi' do
  before do
    # run before each test
    @api_instance = Solifyn::DigitalFileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DigitalFileApi' do
    it 'should create an instance of DigitalFileApi' do
      expect(@api_instance).to be_instance_of(Solifyn::DigitalFileApi)
    end
  end

  # unit tests for digital_file_controller_create
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'digital_file_controller_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for digital_file_controller_find_all
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'digital_file_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for digital_file_controller_remove
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'digital_file_controller_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
