=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::DisputesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DisputesApi' do
  before do
    # run before each test
    @api_instance = Solifyn::DisputesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DisputesApi' do
    it 'should create an instance of DisputesApi' do
      expect(@api_instance).to be_instance_of(Solifyn::DisputesApi)
    end
  end

  # unit tests for disputes_generate_report
  # Generate Dispute CSV Report
  # Generates a downloadable CSV report of disputes matching the filters.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :created_at_gte Filter disputes created after this ISO date-time string
  # @option opts [String] :created_at_lte Filter disputes created before this ISO date-time string
  # @option opts [String] :status Filter disputes by status
  # @return [nil]
  describe 'disputes_generate_report test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disputes_get
  # Retrieve Dispute
  # Retrieve details of a specific dispute by ID.
  # @param id The dispute ID
  # @param [Hash] opts the optional parameters
  # @return [Dispute]
  describe 'disputes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disputes_list
  # List Disputes
  # Retrieve disputes associated with the active business.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page Page number for pagination
  # @option opts [String] :limit Page size limit for pagination
  # @option opts [String] :status Filter disputes by status
  # @option opts [String] :type Filter by type: dispute or alert
  # @return [DisputeList]
  describe 'disputes_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disputes_submit_evidence
  # Submit Dispute Evidence
  # Finalize and submit the uploaded evidence for review.
  # @param id The dispute ID
  # @param [Hash] opts the optional parameters
  # @return [Dispute]
  describe 'disputes_submit_evidence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disputes_update_evidence
  # Update Dispute Evidence
  # Upload and update evidence attachments for a dispute.
  # @param id The dispute ID
  # @param dispute_evidence_update 
  # @param [Hash] opts the optional parameters
  # @return [Dispute]
  describe 'disputes_update_evidence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disputes_upload_evidence_file
  # Upload Evidence File
  # Upload a support file (image, PDF, video) to use as dispute evidence.
  # @param file The evidence file to upload (Max 25MB: JPEG, PNG, GIF, WEBP, PDF, MP4, WEBM, QuickTime)
  # @param [Hash] opts the optional parameters
  # @return [DisputeFileUpload]
  describe 'disputes_upload_evidence_file test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
