=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::FramerIntegrationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FramerIntegrationApi' do
  before do
    # run before each test
    @api_instance = Solifyn::FramerIntegrationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FramerIntegrationApi' do
    it 'should create an instance of FramerIntegrationApi' do
      expect(@api_instance).to be_instance_of(Solifyn::FramerIntegrationApi)
    end
  end

  # unit tests for framer_create_template
  # Create Framer Template
  # Registers a new Framer template with its public remix link for the active business.
  # @param create_framer_template_dto 
  # @param [Hash] opts the optional parameters
  # @return [FramerTemplateResponseDto]
  describe 'framer_create_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for framer_delete_template
  # Delete Framer Template
  # Deletes a registered Framer template for the active business.
  # @param id The Framer template ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'framer_delete_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for framer_get_template
  # Retrieve Framer Template
  # Retrieves details of a specific registered Framer template.
  # @param id The Framer template ID
  # @param [Hash] opts the optional parameters
  # @return [FramerTemplateResponseDto]
  describe 'framer_get_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for framer_list_templates
  # List Framer Templates
  # Retrieves all registered Framer templates for the active business.
  # @param [Hash] opts the optional parameters
  # @return [Array<FramerTemplateResponseDto>]
  describe 'framer_list_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for framer_update_template
  # Update Framer Template
  # Updates a registered Framer template for the active business.
  # @param id The Framer template ID
  # @param update_framer_template_dto 
  # @param [Hash] opts the optional parameters
  # @return [FramerTemplateResponseDto]
  describe 'framer_update_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
