=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::GitHubIntegrationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GitHubIntegrationApi' do
  before do
    # run before each test
    @api_instance = Solifyn::GitHubIntegrationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GitHubIntegrationApi' do
    it 'should create an instance of GitHubIntegrationApi' do
      expect(@api_instance).to be_instance_of(Solifyn::GitHubIntegrationApi)
    end
  end

  # unit tests for github_get_install_url
  # Get GitHub App Installation URL
  # Generates the URL to install the system-wide GitHub App onto the merchant&#39;s GitHub account/org.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :product_id Optional Product ID to redirect back to after installation
  # @return [nil]
  describe 'github_get_install_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for github_list_repos
  # List Available GitHub Repositories
  # Retrieves all repositories accessible by the merchant&#39;s installed GitHub App.
  # @param [Hash] opts the optional parameters
  # @return [Array<GithubReposResponseDto>]
  describe 'github_list_repos test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
