=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::LicenseKeysClientApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LicenseKeysClientApi' do
  before do
    # run before each test
    @api_instance = Solifyn::LicenseKeysClientApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LicenseKeysClientApi' do
    it 'should create an instance of LicenseKeysClientApi' do
      expect(@api_instance).to be_instance_of(Solifyn::LicenseKeysClientApi)
    end
  end

  # unit tests for licenses_activate
  # Activate License Key
  # Register and activate a device or instance for a specific license key.
  # @param licenses_activate_request 
  # @param [Hash] opts the optional parameters
  # @return [Instance]
  describe 'licenses_activate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for licenses_deactivate
  # Deactivate Instance
  # Deactivate or unregister an active device instance from a license key.
  # @param instance_id The unique device instance ID.
  # @param licenses_deactivate_request 
  # @param [Hash] opts the optional parameters
  # @return [LicensesDeactivate200Response]
  describe 'licenses_deactivate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for licenses_instances
  # Get Active Instances
  # List all active devices or server instances linked to a specific license key.
  # @param license_id The unique license key ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<Instance>]
  describe 'licenses_instances test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for licenses_verify
  # Validate License Key
  # Verify if a software license key is valid, active, and has not exceeded its limits.
  # @param licenses_verify_request 
  # @param [Hash] opts the optional parameters
  # @return [LicenseValidationResponse]
  describe 'licenses_verify test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
