=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::MetersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MetersApi' do
  before do
    # run before each test
    @api_instance = Solifyn::MetersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MetersApi' do
    it 'should create an instance of MetersApi' do
      expect(@api_instance).to be_instance_of(Solifyn::MetersApi)
    end
  end

  # unit tests for events_ingest
  # Ingest Events
  # Ingest usage events for meters.
  # @param meter_ingest_request_dto 
  # @param [Hash] opts the optional parameters
  # @return [MeterIngestResponseDto]
  describe 'events_ingest test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for meters_create
  # Create Meter
  # Create a new usage meter for event-based billing and usage tracking.
  # @param create_meter_dto 
  # @param [Hash] opts the optional parameters
  # @return [MeterResponseDto]
  describe 'meters_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for meters_get
  # Retrieve Meter
  # Retrieve a meter and its most recent usage events.
  # @param id The unique meter ID.
  # @param start_date 
  # @param end_date 
  # @param [Hash] opts the optional parameters
  # @return [MeterDetailResponseDto]
  describe 'meters_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for meters_get_events
  # List Meter Events
  # List recent usage events recorded for a meter.
  # @param id The unique meter ID.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :limit Maximum number of usage events to return.
  # @return [MeterEventsResponseDto]
  describe 'meters_get_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for meters_get_quantities
  # Get Meter Quantities
  # Get aggregated usage quantities for a meter within an optional date range.
  # @param id The unique meter ID.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_date Inclusive start date in ISO 8601 format.
  # @option opts [String] :end_date Inclusive end date in ISO 8601 format.
  # @return [MeterQuantitiesResponseDto]
  describe 'meters_get_quantities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for meters_list
  # List Meters
  # List meters belonging to your active business. You can filter by archived status.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Filter by meter status.
  # @return [Array<MeterResponseDto>]
  describe 'meters_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for meters_update
  # Update Meter
  # Update an existing meter definition.
  # @param id The unique meter ID.
  # @param update_meter_dto 
  # @param [Hash] opts the optional parameters
  # @return [MeterResponseDto]
  describe 'meters_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
