=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::OrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @api_instance = Solifyn::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@api_instance).to be_instance_of(Solifyn::OrdersApi)
    end
  end

  # unit tests for orders_get
  # Retrieve Order
  # Retrieve details of a specific order/payment by ID.
  # @param id The unique order/payment ID.
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'orders_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for orders_get_invoice
  # Get Order Invoice
  # Retrieve the generated invoice details for the specified order.
  # @param id The unique order/payment ID.
  # @param [Hash] opts the optional parameters
  # @return [Invoice]
  describe 'orders_get_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for orders_list
  # List Orders
  # List and query orders/payments belonging to your active business.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :created_at_lte Filter by creation date less than or equal to.
  # @option opts [String] :created_at_gte Filter by creation date greater than or equal to.
  # @option opts [String] :product_id Filter by product identifier.
  # @option opts [String] :customer_id Filter by customer identifier.
  # @option opts [String] :status Filter by order/payment status.
  # @option opts [Float] :page_size Size of a page, defaults to 10. Maximum is 100.
  # @option opts [Float] :page_number Page number, defaults to 1.
  # @return [OrderList]
  describe 'orders_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for orders_update
  # Update Order Billing Address
  # Update the billing details of an existing order.
  # @param id The unique order/payment ID.
  # @param order_update 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'orders_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for refunds_create
  # Create Refund
  # Initiate a full or partial refund for a specific payment/order.
  # @param id The unique order/payment ID.
  # @param order_refund_create 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'refunds_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
