=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Solifyn::SubscriptionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SubscriptionsApi' do
  before do
    # run before each test
    @api_instance = Solifyn::SubscriptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionsApi' do
    it 'should create an instance of SubscriptionsApi' do
      expect(@api_instance).to be_instance_of(Solifyn::SubscriptionsApi)
    end
  end

  # unit tests for subscriptions_action
  # Subscription Action
  # Cancel, pause, resume, or add free days to a customer subscription.
  # @param subscription_id The customer subscription ID
  # @param action The subscription task to execute
  # @param subscription_action 
  # @param [Hash] opts the optional parameters
  # @return [SubscriptionsAction201Response]
  describe 'subscriptions_action test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscriptions_get
  # Retrieve Subscription Details
  # Retrieve detailed information about a subscription and its billing history.
  # @param id The customer subscription ID
  # @param [Hash] opts the optional parameters
  # @return [SubscriptionDetail]
  describe 'subscriptions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscriptions_list
  # List Subscriptions
  # Retrieve a list of customer subscriptions, optionally filtered by customer ID.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id Filter subscriptions by customer ID.
  # @return [SubscriptionList]
  describe 'subscriptions_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
