=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Solifyn::BusinessCreate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Solifyn::BusinessCreate do
  let(:instance) { Solifyn::BusinessCreate.new }

  describe 'test an instance of BusinessCreate' do
    it 'should create an instance of BusinessCreate' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Solifyn::BusinessCreate)
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
