=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Solifyn::CustomerSharedInviteResponseDto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Solifyn::CustomerSharedInviteResponseDto do
  let(:instance) { Solifyn::CustomerSharedInviteResponseDto.new }

  describe 'test an instance of CustomerSharedInviteResponseDto' do
    it 'should create an instance of CustomerSharedInviteResponseDto' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Solifyn::CustomerSharedInviteResponseDto)
    end
  end

  describe 'test attribute "token"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expires_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
