=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Solifyn
  class Business
    # The unique business ID
    attr_accessor :id

    # Title or name of the business
    attr_accessor :title

    # A description explaining what the business does
    attr_accessor :description

    # The Whop Company ID
    attr_accessor :whop_id

    # The merchant owner ID
    attr_accessor :merchant_id

    # Whether the business has been KYC-verified on Whop
    attr_accessor :verified

    # Whether auto-emails are enabled for customers
    attr_accessor :send_customer_emails

    # Total members/customers under this business
    attr_accessor :member_count

    # Whop friendly URL path route
    attr_accessor :route

    # The default currency of the business
    attr_accessor :default_currency

    # Number of published user reviews on Whop
    attr_accessor :published_reviews_count

    # Custom key-value metadata
    attr_accessor :metadata

    # The target audience description
    attr_accessor :target_audience

    # Social links setup
    attr_accessor :social_links

    # Markdown instructions for affiliates
    attr_accessor :affiliate_instructions

    # Whop account creation timestamp
    attr_accessor :whop_created_at

    # Whop account last updated timestamp
    attr_accessor :whop_updated_at

    # Timestamp when the business record was created
    attr_accessor :created_at

    # Timestamp when the business record was last updated
    attr_accessor :updated_at

    # Brand logo image URL resolved from primary brand
    attr_accessor :logo_url

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'title' => :'title',
        :'description' => :'description',
        :'whop_id' => :'whopId',
        :'merchant_id' => :'merchantId',
        :'verified' => :'verified',
        :'send_customer_emails' => :'sendCustomerEmails',
        :'member_count' => :'memberCount',
        :'route' => :'route',
        :'default_currency' => :'defaultCurrency',
        :'published_reviews_count' => :'publishedReviewsCount',
        :'metadata' => :'metadata',
        :'target_audience' => :'targetAudience',
        :'social_links' => :'socialLinks',
        :'affiliate_instructions' => :'affiliateInstructions',
        :'whop_created_at' => :'whopCreatedAt',
        :'whop_updated_at' => :'whopUpdatedAt',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'logo_url' => :'logoUrl'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'title' => :'String',
        :'description' => :'String',
        :'whop_id' => :'String',
        :'merchant_id' => :'String',
        :'verified' => :'Boolean',
        :'send_customer_emails' => :'Boolean',
        :'member_count' => :'Float',
        :'route' => :'String',
        :'default_currency' => :'String',
        :'published_reviews_count' => :'Float',
        :'metadata' => :'Object',
        :'target_audience' => :'String',
        :'social_links' => :'Object',
        :'affiliate_instructions' => :'String',
        :'whop_created_at' => :'Time',
        :'whop_updated_at' => :'Time',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'logo_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Solifyn::Business` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Solifyn::Business`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'whop_id')
        self.whop_id = attributes[:'whop_id']
      else
        self.whop_id = nil
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      else
        self.merchant_id = nil
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      else
        self.verified = nil
      end

      if attributes.key?(:'send_customer_emails')
        self.send_customer_emails = attributes[:'send_customer_emails']
      else
        self.send_customer_emails = nil
      end

      if attributes.key?(:'member_count')
        self.member_count = attributes[:'member_count']
      else
        self.member_count = nil
      end

      if attributes.key?(:'route')
        self.route = attributes[:'route']
      end

      if attributes.key?(:'default_currency')
        self.default_currency = attributes[:'default_currency']
      else
        self.default_currency = nil
      end

      if attributes.key?(:'published_reviews_count')
        self.published_reviews_count = attributes[:'published_reviews_count']
      else
        self.published_reviews_count = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'target_audience')
        self.target_audience = attributes[:'target_audience']
      end

      if attributes.key?(:'social_links')
        self.social_links = attributes[:'social_links']
      end

      if attributes.key?(:'affiliate_instructions')
        self.affiliate_instructions = attributes[:'affiliate_instructions']
      end

      if attributes.key?(:'whop_created_at')
        self.whop_created_at = attributes[:'whop_created_at']
      end

      if attributes.key?(:'whop_updated_at')
        self.whop_updated_at = attributes[:'whop_updated_at']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'logo_url')
        self.logo_url = attributes[:'logo_url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @whop_id.nil?
        invalid_properties.push('invalid value for "whop_id", whop_id cannot be nil.')
      end

      if @merchant_id.nil?
        invalid_properties.push('invalid value for "merchant_id", merchant_id cannot be nil.')
      end

      if @verified.nil?
        invalid_properties.push('invalid value for "verified", verified cannot be nil.')
      end

      if @send_customer_emails.nil?
        invalid_properties.push('invalid value for "send_customer_emails", send_customer_emails cannot be nil.')
      end

      if @member_count.nil?
        invalid_properties.push('invalid value for "member_count", member_count cannot be nil.')
      end

      if @default_currency.nil?
        invalid_properties.push('invalid value for "default_currency", default_currency cannot be nil.')
      end

      if @published_reviews_count.nil?
        invalid_properties.push('invalid value for "published_reviews_count", published_reviews_count cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @title.nil?
      return false if @whop_id.nil?
      return false if @merchant_id.nil?
      return false if @verified.nil?
      return false if @send_customer_emails.nil?
      return false if @member_count.nil?
      return false if @default_currency.nil?
      return false if @published_reviews_count.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          title == o.title &&
          description == o.description &&
          whop_id == o.whop_id &&
          merchant_id == o.merchant_id &&
          verified == o.verified &&
          send_customer_emails == o.send_customer_emails &&
          member_count == o.member_count &&
          route == o.route &&
          default_currency == o.default_currency &&
          published_reviews_count == o.published_reviews_count &&
          metadata == o.metadata &&
          target_audience == o.target_audience &&
          social_links == o.social_links &&
          affiliate_instructions == o.affiliate_instructions &&
          whop_created_at == o.whop_created_at &&
          whop_updated_at == o.whop_updated_at &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          logo_url == o.logo_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, title, description, whop_id, merchant_id, verified, send_customer_emails, member_count, route, default_currency, published_reviews_count, metadata, target_audience, social_links, affiliate_instructions, whop_created_at, whop_updated_at, created_at, updated_at, logo_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Solifyn.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
