=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Solifyn
  class CollectionProductDto
    # The unique identifier (ID) of the product.
    attr_accessor :id

    # The display name of the product.
    attr_accessor :name

    # The price amount of the product (e.g. 29.00).
    attr_accessor :price

    # The three-letter ISO currency code (e.g. USD, VND, EUR).
    attr_accessor :currency

    # A comprehensive rich text description of the product.
    attr_accessor :description

    # The lifecycle status of the product (e.g. ACTIVE, ARCHIVED).
    attr_accessor :status

    # URL of the product cover image.
    attr_accessor :image_url

    # The tax classification for the product.
    attr_accessor :tax_category

    # Pricing model of the product.
    attr_accessor :pricing_type

    # Discount value as a percentage or fixed amount.
    attr_accessor :discount

    # Indicates if the product issues a cryptographically secure software license key upon checkout completion.
    attr_accessor :has_license_key

    # Whether the product includes digital file downloads upon purchase.
    attr_accessor :has_digital_delivery

    # Whether the product price already includes applicable sales taxes.
    attr_accessor :is_tax_inclusive

    # The subscription billing cycle interval in days (for subscription products).
    attr_accessor :billing_period

    # Trial duration in days for subscription products.
    attr_accessor :trial_period_days

    # Automatic expiration period in days for the subscription entitlement.
    attr_accessor :expiration_days

    # Custom text displayed on customer credit card statements for purchases of this product.
    attr_accessor :statement_descriptor

    # Indicates if customers are allowed to enter a custom pricing amount at checkout.
    attr_accessor :pay_what_you_want

    # Custom developer metadata key-value pairs associated with the product.
    attr_accessor :metadata

    # Custom form field questions to ask the customer during checkout.
    attr_accessor :custom_fields

    # Available stock quantity, or null for unlimited inventory.
    attr_accessor :stock

    # Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true).
    attr_accessor :activation_limit

    # Defines if the product is listed publicly on the merchant's storefront template.
    attr_accessor :is_listed

    # Whether the product is free.
    attr_accessor :is_free

    # Timestamp indicating exactly when the product was created.
    attr_accessor :created_at

    # Timestamp indicating when the product was last modified.
    attr_accessor :updated_at

    # Indicates if the product has been permanently deleted.
    attr_accessor :is_permanently_deleted

    # Optional brand identifier.
    attr_accessor :brand_id

    # Secure link for digital delivery.
    attr_accessor :digital_link

    # Special instructions provided upon purchase.
    attr_accessor :instructions

    # Custom message displayed when a license key is activated.
    attr_accessor :activation_message

    # Number of hours until the license key expires.
    attr_accessor :expiry_hours

    # The unique identifier of the business owning this product.
    attr_accessor :business_id

    # Quantity of the product in the collection
    attr_accessor :quantity

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'price' => :'price',
        :'currency' => :'currency',
        :'description' => :'description',
        :'status' => :'status',
        :'image_url' => :'imageUrl',
        :'tax_category' => :'taxCategory',
        :'pricing_type' => :'pricingType',
        :'discount' => :'discount',
        :'has_license_key' => :'hasLicenseKey',
        :'has_digital_delivery' => :'hasDigitalDelivery',
        :'is_tax_inclusive' => :'isTaxInclusive',
        :'billing_period' => :'billingPeriod',
        :'trial_period_days' => :'trialPeriodDays',
        :'expiration_days' => :'expirationDays',
        :'statement_descriptor' => :'statementDescriptor',
        :'pay_what_you_want' => :'payWhatYouWant',
        :'metadata' => :'metadata',
        :'custom_fields' => :'customFields',
        :'stock' => :'stock',
        :'activation_limit' => :'activationLimit',
        :'is_listed' => :'isListed',
        :'is_free' => :'isFree',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'is_permanently_deleted' => :'isPermanentlyDeleted',
        :'brand_id' => :'brandId',
        :'digital_link' => :'digitalLink',
        :'instructions' => :'instructions',
        :'activation_message' => :'activationMessage',
        :'expiry_hours' => :'expiryHours',
        :'business_id' => :'businessId',
        :'quantity' => :'quantity'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'price' => :'Float',
        :'currency' => :'String',
        :'description' => :'String',
        :'status' => :'String',
        :'image_url' => :'String',
        :'tax_category' => :'String',
        :'pricing_type' => :'String',
        :'discount' => :'Float',
        :'has_license_key' => :'Boolean',
        :'has_digital_delivery' => :'Boolean',
        :'is_tax_inclusive' => :'Boolean',
        :'billing_period' => :'Integer',
        :'trial_period_days' => :'Integer',
        :'expiration_days' => :'Integer',
        :'statement_descriptor' => :'String',
        :'pay_what_you_want' => :'Boolean',
        :'metadata' => :'Hash<String, String>',
        :'custom_fields' => :'Array<Object>',
        :'stock' => :'Integer',
        :'activation_limit' => :'Integer',
        :'is_listed' => :'Boolean',
        :'is_free' => :'Boolean',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'is_permanently_deleted' => :'Boolean',
        :'brand_id' => :'String',
        :'digital_link' => :'String',
        :'instructions' => :'String',
        :'activation_message' => :'String',
        :'expiry_hours' => :'Integer',
        :'business_id' => :'String',
        :'quantity' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Solifyn::CollectionProductDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Solifyn::CollectionProductDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      else
        self.price = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      else
        self.image_url = nil
      end

      if attributes.key?(:'tax_category')
        self.tax_category = attributes[:'tax_category']
      else
        self.tax_category = nil
      end

      if attributes.key?(:'pricing_type')
        self.pricing_type = attributes[:'pricing_type']
      else
        self.pricing_type = nil
      end

      if attributes.key?(:'discount')
        self.discount = attributes[:'discount']
      else
        self.discount = nil
      end

      if attributes.key?(:'has_license_key')
        self.has_license_key = attributes[:'has_license_key']
      else
        self.has_license_key = nil
      end

      if attributes.key?(:'has_digital_delivery')
        self.has_digital_delivery = attributes[:'has_digital_delivery']
      else
        self.has_digital_delivery = nil
      end

      if attributes.key?(:'is_tax_inclusive')
        self.is_tax_inclusive = attributes[:'is_tax_inclusive']
      else
        self.is_tax_inclusive = nil
      end

      if attributes.key?(:'billing_period')
        self.billing_period = attributes[:'billing_period']
      else
        self.billing_period = nil
      end

      if attributes.key?(:'trial_period_days')
        self.trial_period_days = attributes[:'trial_period_days']
      else
        self.trial_period_days = nil
      end

      if attributes.key?(:'expiration_days')
        self.expiration_days = attributes[:'expiration_days']
      else
        self.expiration_days = nil
      end

      if attributes.key?(:'statement_descriptor')
        self.statement_descriptor = attributes[:'statement_descriptor']
      else
        self.statement_descriptor = nil
      end

      if attributes.key?(:'pay_what_you_want')
        self.pay_what_you_want = attributes[:'pay_what_you_want']
      else
        self.pay_what_you_want = nil
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      else
        self.metadata = nil
      end

      if attributes.key?(:'custom_fields')
        if (value = attributes[:'custom_fields']).is_a?(Array)
          self.custom_fields = value
        end
      else
        self.custom_fields = nil
      end

      if attributes.key?(:'stock')
        self.stock = attributes[:'stock']
      else
        self.stock = nil
      end

      if attributes.key?(:'activation_limit')
        self.activation_limit = attributes[:'activation_limit']
      else
        self.activation_limit = nil
      end

      if attributes.key?(:'is_listed')
        self.is_listed = attributes[:'is_listed']
      else
        self.is_listed = nil
      end

      if attributes.key?(:'is_free')
        self.is_free = attributes[:'is_free']
      else
        self.is_free = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'is_permanently_deleted')
        self.is_permanently_deleted = attributes[:'is_permanently_deleted']
      else
        self.is_permanently_deleted = nil
      end

      if attributes.key?(:'brand_id')
        self.brand_id = attributes[:'brand_id']
      else
        self.brand_id = nil
      end

      if attributes.key?(:'digital_link')
        self.digital_link = attributes[:'digital_link']
      else
        self.digital_link = nil
      end

      if attributes.key?(:'instructions')
        self.instructions = attributes[:'instructions']
      else
        self.instructions = nil
      end

      if attributes.key?(:'activation_message')
        self.activation_message = attributes[:'activation_message']
      else
        self.activation_message = nil
      end

      if attributes.key?(:'expiry_hours')
        self.expiry_hours = attributes[:'expiry_hours']
      else
        self.expiry_hours = nil
      end

      if attributes.key?(:'business_id')
        self.business_id = attributes[:'business_id']
      else
        self.business_id = nil
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      else
        self.quantity = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @price.nil?
        invalid_properties.push('invalid value for "price", price cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @image_url.nil?
        invalid_properties.push('invalid value for "image_url", image_url cannot be nil.')
      end

      if @tax_category.nil?
        invalid_properties.push('invalid value for "tax_category", tax_category cannot be nil.')
      end

      if @pricing_type.nil?
        invalid_properties.push('invalid value for "pricing_type", pricing_type cannot be nil.')
      end

      if @discount.nil?
        invalid_properties.push('invalid value for "discount", discount cannot be nil.')
      end

      if @has_license_key.nil?
        invalid_properties.push('invalid value for "has_license_key", has_license_key cannot be nil.')
      end

      if @has_digital_delivery.nil?
        invalid_properties.push('invalid value for "has_digital_delivery", has_digital_delivery cannot be nil.')
      end

      if @is_tax_inclusive.nil?
        invalid_properties.push('invalid value for "is_tax_inclusive", is_tax_inclusive cannot be nil.')
      end

      if @billing_period.nil?
        invalid_properties.push('invalid value for "billing_period", billing_period cannot be nil.')
      end

      if @trial_period_days.nil?
        invalid_properties.push('invalid value for "trial_period_days", trial_period_days cannot be nil.')
      end

      if @expiration_days.nil?
        invalid_properties.push('invalid value for "expiration_days", expiration_days cannot be nil.')
      end

      if @statement_descriptor.nil?
        invalid_properties.push('invalid value for "statement_descriptor", statement_descriptor cannot be nil.')
      end

      if @pay_what_you_want.nil?
        invalid_properties.push('invalid value for "pay_what_you_want", pay_what_you_want cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @custom_fields.nil?
        invalid_properties.push('invalid value for "custom_fields", custom_fields cannot be nil.')
      end

      if @stock.nil?
        invalid_properties.push('invalid value for "stock", stock cannot be nil.')
      end

      if @activation_limit.nil?
        invalid_properties.push('invalid value for "activation_limit", activation_limit cannot be nil.')
      end

      if @is_listed.nil?
        invalid_properties.push('invalid value for "is_listed", is_listed cannot be nil.')
      end

      if @is_free.nil?
        invalid_properties.push('invalid value for "is_free", is_free cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @is_permanently_deleted.nil?
        invalid_properties.push('invalid value for "is_permanently_deleted", is_permanently_deleted cannot be nil.')
      end

      if @brand_id.nil?
        invalid_properties.push('invalid value for "brand_id", brand_id cannot be nil.')
      end

      if @digital_link.nil?
        invalid_properties.push('invalid value for "digital_link", digital_link cannot be nil.')
      end

      if @instructions.nil?
        invalid_properties.push('invalid value for "instructions", instructions cannot be nil.')
      end

      if @activation_message.nil?
        invalid_properties.push('invalid value for "activation_message", activation_message cannot be nil.')
      end

      if @expiry_hours.nil?
        invalid_properties.push('invalid value for "expiry_hours", expiry_hours cannot be nil.')
      end

      if @business_id.nil?
        invalid_properties.push('invalid value for "business_id", business_id cannot be nil.')
      end

      if @quantity.nil?
        invalid_properties.push('invalid value for "quantity", quantity cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @price.nil?
      return false if @currency.nil?
      return false if @status.nil?
      return false if @image_url.nil?
      return false if @tax_category.nil?
      tax_category_validator = EnumAttributeValidator.new('String', ["digital_products", "saas", "physical_products", "service"])
      return false unless tax_category_validator.valid?(@tax_category)
      return false if @pricing_type.nil?
      pricing_type_validator = EnumAttributeValidator.new('String', ["usage_based", "one_time", "renewal"])
      return false unless pricing_type_validator.valid?(@pricing_type)
      return false if @discount.nil?
      return false if @has_license_key.nil?
      return false if @has_digital_delivery.nil?
      return false if @is_tax_inclusive.nil?
      return false if @billing_period.nil?
      return false if @trial_period_days.nil?
      return false if @expiration_days.nil?
      return false if @statement_descriptor.nil?
      return false if @pay_what_you_want.nil?
      return false if @metadata.nil?
      return false if @custom_fields.nil?
      return false if @stock.nil?
      return false if @activation_limit.nil?
      return false if @is_listed.nil?
      return false if @is_free.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @is_permanently_deleted.nil?
      return false if @brand_id.nil?
      return false if @digital_link.nil?
      return false if @instructions.nil?
      return false if @activation_message.nil?
      return false if @expiry_hours.nil?
      return false if @business_id.nil?
      return false if @quantity.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tax_category Object to be assigned
    def tax_category=(tax_category)
      validator = EnumAttributeValidator.new('String', ["digital_products", "saas", "physical_products", "service"])
      unless validator.valid?(tax_category)
        fail ArgumentError, "invalid value for \"tax_category\", must be one of #{validator.allowable_values}."
      end
      @tax_category = tax_category
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] pricing_type Object to be assigned
    def pricing_type=(pricing_type)
      validator = EnumAttributeValidator.new('String', ["usage_based", "one_time", "renewal"])
      unless validator.valid?(pricing_type)
        fail ArgumentError, "invalid value for \"pricing_type\", must be one of #{validator.allowable_values}."
      end
      @pricing_type = pricing_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          price == o.price &&
          currency == o.currency &&
          description == o.description &&
          status == o.status &&
          image_url == o.image_url &&
          tax_category == o.tax_category &&
          pricing_type == o.pricing_type &&
          discount == o.discount &&
          has_license_key == o.has_license_key &&
          has_digital_delivery == o.has_digital_delivery &&
          is_tax_inclusive == o.is_tax_inclusive &&
          billing_period == o.billing_period &&
          trial_period_days == o.trial_period_days &&
          expiration_days == o.expiration_days &&
          statement_descriptor == o.statement_descriptor &&
          pay_what_you_want == o.pay_what_you_want &&
          metadata == o.metadata &&
          custom_fields == o.custom_fields &&
          stock == o.stock &&
          activation_limit == o.activation_limit &&
          is_listed == o.is_listed &&
          is_free == o.is_free &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          is_permanently_deleted == o.is_permanently_deleted &&
          brand_id == o.brand_id &&
          digital_link == o.digital_link &&
          instructions == o.instructions &&
          activation_message == o.activation_message &&
          expiry_hours == o.expiry_hours &&
          business_id == o.business_id &&
          quantity == o.quantity
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, price, currency, description, status, image_url, tax_category, pricing_type, discount, has_license_key, has_digital_delivery, is_tax_inclusive, billing_period, trial_period_days, expiration_days, statement_descriptor, pay_what_you_want, metadata, custom_fields, stock, activation_limit, is_listed, is_free, created_at, updated_at, is_permanently_deleted, brand_id, digital_link, instructions, activation_message, expiry_hours, business_id, quantity].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Solifyn.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
