=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Solifyn
  # Represents a cryptographically secure software license key issued to a customer upon purchase or manual issuance.
  class License
    # The unique prefix-based identifier of the license key.
    attr_accessor :id

    # The cryptographically generated license key string delivered to the customer.
    attr_accessor :key

    # Lifecycle status of the license. ACTIVE = active. DISABLED = suspended. REVOKED = hard-revoked.
    attr_accessor :status

    # The unique identifier associated with the business this license belongs to.
    attr_accessor :business_id

    # The unique ID of the product this license key is associated with.
    attr_accessor :product_id

    # The unique payment identifier that triggered the issuance of this license key.
    attr_accessor :payment_id

    # The unique customer identifier (ID) who received this license key.
    attr_accessor :customer_id

    # Maximum number of simultaneous active device instances allowed for this license. Null means unlimited.
    attr_accessor :activation_limit

    # Optional message displayed to the customer upon successful activation.
    attr_accessor :activation_message

    # Running count of how many times this license key has been activated.
    attr_accessor :instances_count

    # Relative expiry duration in hours from the time of issuance.
    attr_accessor :expiry_hours

    # Absolute expiration timestamp. The license becomes invalid after this point.
    attr_accessor :expires_at

    # Optional custom metadata filters associated with the license.
    attr_accessor :filters

    # Indicates if the license key is archived.
    attr_accessor :archived

    # Timestamp indicating exactly when the license key was issued.
    attr_accessor :created_at

    # Timestamp indicating when the license key was last modified.
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'key' => :'key',
        :'status' => :'status',
        :'business_id' => :'businessId',
        :'product_id' => :'productId',
        :'payment_id' => :'paymentId',
        :'customer_id' => :'customerId',
        :'activation_limit' => :'activationLimit',
        :'activation_message' => :'activationMessage',
        :'instances_count' => :'instancesCount',
        :'expiry_hours' => :'expiryHours',
        :'expires_at' => :'expiresAt',
        :'filters' => :'filters',
        :'archived' => :'archived',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'key' => :'String',
        :'status' => :'String',
        :'business_id' => :'String',
        :'product_id' => :'String',
        :'payment_id' => :'String',
        :'customer_id' => :'String',
        :'activation_limit' => :'Float',
        :'activation_message' => :'String',
        :'instances_count' => :'Float',
        :'expiry_hours' => :'Float',
        :'expires_at' => :'String',
        :'filters' => :'Object',
        :'archived' => :'Boolean',
        :'created_at' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'product_id',
        :'payment_id',
        :'customer_id',
        :'activation_limit',
        :'activation_message',
        :'expiry_hours',
        :'expires_at',
        :'filters',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Solifyn::License` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Solifyn::License`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'key')
        self.key = attributes[:'key']
      else
        self.key = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'business_id')
        self.business_id = attributes[:'business_id']
      else
        self.business_id = nil
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      else
        self.product_id = nil
      end

      if attributes.key?(:'payment_id')
        self.payment_id = attributes[:'payment_id']
      else
        self.payment_id = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      else
        self.customer_id = nil
      end

      if attributes.key?(:'activation_limit')
        self.activation_limit = attributes[:'activation_limit']
      else
        self.activation_limit = nil
      end

      if attributes.key?(:'activation_message')
        self.activation_message = attributes[:'activation_message']
      else
        self.activation_message = nil
      end

      if attributes.key?(:'instances_count')
        self.instances_count = attributes[:'instances_count']
      else
        self.instances_count = nil
      end

      if attributes.key?(:'expiry_hours')
        self.expiry_hours = attributes[:'expiry_hours']
      else
        self.expiry_hours = nil
      end

      if attributes.key?(:'expires_at')
        self.expires_at = attributes[:'expires_at']
      else
        self.expires_at = nil
      end

      if attributes.key?(:'filters')
        self.filters = attributes[:'filters']
      else
        self.filters = nil
      end

      if attributes.key?(:'archived')
        self.archived = attributes[:'archived']
      else
        self.archived = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @key.nil?
        invalid_properties.push('invalid value for "key", key cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @business_id.nil?
        invalid_properties.push('invalid value for "business_id", business_id cannot be nil.')
      end

      if @instances_count.nil?
        invalid_properties.push('invalid value for "instances_count", instances_count cannot be nil.')
      end

      if @archived.nil?
        invalid_properties.push('invalid value for "archived", archived cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @key.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["ACTIVE", "DISABLED", "REVOKED"])
      return false unless status_validator.valid?(@status)
      return false if @business_id.nil?
      return false if @instances_count.nil?
      return false if @archived.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ACTIVE", "DISABLED", "REVOKED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          key == o.key &&
          status == o.status &&
          business_id == o.business_id &&
          product_id == o.product_id &&
          payment_id == o.payment_id &&
          customer_id == o.customer_id &&
          activation_limit == o.activation_limit &&
          activation_message == o.activation_message &&
          instances_count == o.instances_count &&
          expiry_hours == o.expiry_hours &&
          expires_at == o.expires_at &&
          filters == o.filters &&
          archived == o.archived &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, key, status, business_id, product_id, payment_id, customer_id, activation_limit, activation_message, instances_count, expiry_hours, expires_at, filters, archived, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Solifyn.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
