=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Solifyn
  # Represents an order (payment) processed under your business, containing customer, billing, product cart, and refund details.
  class Order
    # Unique internal database identifier.
    attr_accessor :id

    # The invoice print URL.
    attr_accessor :invoice_url

    # Customer details.
    attr_accessor :customer

    # Total paid amount in cents.
    attr_accessor :total_amount

    # Subtotal amount in cents.
    attr_accessor :subtotal

    # Tax amount in cents.
    attr_accessor :tax_amount

    # Application fee in cents.
    attr_accessor :application_fee

    # Net amount after fees in cents.
    attr_accessor :amount_after_fees

    # Currency code.
    attr_accessor :currency

    # Current status of the payment.
    attr_accessor :status

    # Payment creation timestamp.
    attr_accessor :created_at

    # Payment completion/paid timestamp.
    attr_accessor :paid_at

    # Payment method utilized.
    attr_accessor :payment_method

    # Last four digits of card used.
    attr_accessor :card_last_four

    # Card network/brand.
    attr_accessor :card_network

    # Card type.
    attr_accessor :card_type

    # Billing address details.
    attr_accessor :billing

    # Products purchased in this order.
    attr_accessor :product_cart

    # Custom metadata payload associated with this payment.
    attr_accessor :metadata

    # Order details snapshot.
    attr_accessor :order

    # Indicates whether the order is eligible for refund.
    attr_accessor :refundable

    # List of refunds associated with this payment.
    attr_accessor :refunds

    # Business unique ID identifier.
    attr_accessor :business_id

    # Business display title/name.
    attr_accessor :business_name

    # Billing reason detail.
    attr_accessor :billing_reason

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'invoice_url' => :'invoice_url',
        :'customer' => :'customer',
        :'total_amount' => :'total_amount',
        :'subtotal' => :'subtotal',
        :'tax_amount' => :'tax_amount',
        :'application_fee' => :'application_fee',
        :'amount_after_fees' => :'amount_after_fees',
        :'currency' => :'currency',
        :'status' => :'status',
        :'created_at' => :'created_at',
        :'paid_at' => :'paidAt',
        :'payment_method' => :'payment_method',
        :'card_last_four' => :'card_last_four',
        :'card_network' => :'card_network',
        :'card_type' => :'card_type',
        :'billing' => :'billing',
        :'product_cart' => :'product_cart',
        :'metadata' => :'metadata',
        :'order' => :'order',
        :'refundable' => :'refundable',
        :'refunds' => :'refunds',
        :'business_id' => :'businessId',
        :'business_name' => :'businessName',
        :'billing_reason' => :'billing_reason'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'invoice_url' => :'String',
        :'customer' => :'OrderCustomer',
        :'total_amount' => :'Integer',
        :'subtotal' => :'Integer',
        :'tax_amount' => :'Integer',
        :'application_fee' => :'Integer',
        :'amount_after_fees' => :'Integer',
        :'currency' => :'String',
        :'status' => :'String',
        :'created_at' => :'Time',
        :'paid_at' => :'Time',
        :'payment_method' => :'String',
        :'card_last_four' => :'String',
        :'card_network' => :'String',
        :'card_type' => :'String',
        :'billing' => :'OrderBilling',
        :'product_cart' => :'Array<OrderProductCart>',
        :'metadata' => :'Object',
        :'order' => :'OrderDetail',
        :'refundable' => :'Boolean',
        :'refunds' => :'Array<OrderRefund>',
        :'business_id' => :'String',
        :'business_name' => :'String',
        :'billing_reason' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Solifyn::Order` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Solifyn::Order`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'invoice_url')
        self.invoice_url = attributes[:'invoice_url']
      else
        self.invoice_url = nil
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      else
        self.customer = nil
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      else
        self.total_amount = nil
      end

      if attributes.key?(:'subtotal')
        self.subtotal = attributes[:'subtotal']
      else
        self.subtotal = nil
      end

      if attributes.key?(:'tax_amount')
        self.tax_amount = attributes[:'tax_amount']
      else
        self.tax_amount = nil
      end

      if attributes.key?(:'application_fee')
        self.application_fee = attributes[:'application_fee']
      else
        self.application_fee = nil
      end

      if attributes.key?(:'amount_after_fees')
        self.amount_after_fees = attributes[:'amount_after_fees']
      else
        self.amount_after_fees = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'paid_at')
        self.paid_at = attributes[:'paid_at']
      end

      if attributes.key?(:'payment_method')
        self.payment_method = attributes[:'payment_method']
      else
        self.payment_method = nil
      end

      if attributes.key?(:'card_last_four')
        self.card_last_four = attributes[:'card_last_four']
      end

      if attributes.key?(:'card_network')
        self.card_network = attributes[:'card_network']
      end

      if attributes.key?(:'card_type')
        self.card_type = attributes[:'card_type']
      end

      if attributes.key?(:'billing')
        self.billing = attributes[:'billing']
      end

      if attributes.key?(:'product_cart')
        if (value = attributes[:'product_cart']).is_a?(Array)
          self.product_cart = value
        end
      else
        self.product_cart = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'order')
        self.order = attributes[:'order']
      end

      if attributes.key?(:'refundable')
        self.refundable = attributes[:'refundable']
      else
        self.refundable = nil
      end

      if attributes.key?(:'refunds')
        if (value = attributes[:'refunds']).is_a?(Array)
          self.refunds = value
        end
      end

      if attributes.key?(:'business_id')
        self.business_id = attributes[:'business_id']
      else
        self.business_id = nil
      end

      if attributes.key?(:'business_name')
        self.business_name = attributes[:'business_name']
      else
        self.business_name = nil
      end

      if attributes.key?(:'billing_reason')
        self.billing_reason = attributes[:'billing_reason']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @invoice_url.nil?
        invalid_properties.push('invalid value for "invoice_url", invoice_url cannot be nil.')
      end

      if @customer.nil?
        invalid_properties.push('invalid value for "customer", customer cannot be nil.')
      end

      if @total_amount.nil?
        invalid_properties.push('invalid value for "total_amount", total_amount cannot be nil.')
      end

      if @subtotal.nil?
        invalid_properties.push('invalid value for "subtotal", subtotal cannot be nil.')
      end

      if @tax_amount.nil?
        invalid_properties.push('invalid value for "tax_amount", tax_amount cannot be nil.')
      end

      if @application_fee.nil?
        invalid_properties.push('invalid value for "application_fee", application_fee cannot be nil.')
      end

      if @amount_after_fees.nil?
        invalid_properties.push('invalid value for "amount_after_fees", amount_after_fees cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @payment_method.nil?
        invalid_properties.push('invalid value for "payment_method", payment_method cannot be nil.')
      end

      if @product_cart.nil?
        invalid_properties.push('invalid value for "product_cart", product_cart cannot be nil.')
      end

      if @refundable.nil?
        invalid_properties.push('invalid value for "refundable", refundable cannot be nil.')
      end

      if @business_id.nil?
        invalid_properties.push('invalid value for "business_id", business_id cannot be nil.')
      end

      if @business_name.nil?
        invalid_properties.push('invalid value for "business_name", business_name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @invoice_url.nil?
      return false if @customer.nil?
      return false if @total_amount.nil?
      return false if @subtotal.nil?
      return false if @tax_amount.nil?
      return false if @application_fee.nil?
      return false if @amount_after_fees.nil?
      return false if @currency.nil?
      return false if @status.nil?
      return false if @created_at.nil?
      return false if @payment_method.nil?
      return false if @product_cart.nil?
      return false if @refundable.nil?
      return false if @business_id.nil?
      return false if @business_name.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          invoice_url == o.invoice_url &&
          customer == o.customer &&
          total_amount == o.total_amount &&
          subtotal == o.subtotal &&
          tax_amount == o.tax_amount &&
          application_fee == o.application_fee &&
          amount_after_fees == o.amount_after_fees &&
          currency == o.currency &&
          status == o.status &&
          created_at == o.created_at &&
          paid_at == o.paid_at &&
          payment_method == o.payment_method &&
          card_last_four == o.card_last_four &&
          card_network == o.card_network &&
          card_type == o.card_type &&
          billing == o.billing &&
          product_cart == o.product_cart &&
          metadata == o.metadata &&
          order == o.order &&
          refundable == o.refundable &&
          refunds == o.refunds &&
          business_id == o.business_id &&
          business_name == o.business_name &&
          billing_reason == o.billing_reason
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, invoice_url, customer, total_amount, subtotal, tax_amount, application_fee, amount_after_fees, currency, status, created_at, paid_at, payment_method, card_last_four, card_network, card_type, billing, product_cart, metadata, order, refundable, refunds, business_id, business_name, billing_reason].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Solifyn.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
