=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Solifyn
  # Represents the detailed cost and billing impact of adjusting subscription seat add-on quantities.
  class SubscriptionSeatAdjustment
    # Indicates if the seat adjustment was successful
    attr_accessor :success

    # The customer subscription ID
    attr_accessor :subscription_id

    # The unique ID of the addon product
    attr_accessor :addon_product_id

    # The previous seat quantity
    attr_accessor :old_quantity

    # The new seat quantity after adjustment
    attr_accessor :new_quantity

    # The difference in seat quantity
    attr_accessor :quantity_delta

    # The proration strategy type applied
    attr_accessor :proration_type

    # Calculated pro-rata price cost impact in currency unit (charged or credited)
    attr_accessor :cost_impact

    # Billing currency
    attr_accessor :currency

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'success' => :'success',
        :'subscription_id' => :'subscriptionId',
        :'addon_product_id' => :'addonProductId',
        :'old_quantity' => :'oldQuantity',
        :'new_quantity' => :'newQuantity',
        :'quantity_delta' => :'quantityDelta',
        :'proration_type' => :'prorationType',
        :'cost_impact' => :'costImpact',
        :'currency' => :'currency'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'success' => :'Boolean',
        :'subscription_id' => :'String',
        :'addon_product_id' => :'String',
        :'old_quantity' => :'Float',
        :'new_quantity' => :'Float',
        :'quantity_delta' => :'Float',
        :'proration_type' => :'String',
        :'cost_impact' => :'Float',
        :'currency' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Solifyn::SubscriptionSeatAdjustment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Solifyn::SubscriptionSeatAdjustment`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'success')
        self.success = attributes[:'success']
      else
        self.success = nil
      end

      if attributes.key?(:'subscription_id')
        self.subscription_id = attributes[:'subscription_id']
      else
        self.subscription_id = nil
      end

      if attributes.key?(:'addon_product_id')
        self.addon_product_id = attributes[:'addon_product_id']
      else
        self.addon_product_id = nil
      end

      if attributes.key?(:'old_quantity')
        self.old_quantity = attributes[:'old_quantity']
      else
        self.old_quantity = nil
      end

      if attributes.key?(:'new_quantity')
        self.new_quantity = attributes[:'new_quantity']
      else
        self.new_quantity = nil
      end

      if attributes.key?(:'quantity_delta')
        self.quantity_delta = attributes[:'quantity_delta']
      else
        self.quantity_delta = nil
      end

      if attributes.key?(:'proration_type')
        self.proration_type = attributes[:'proration_type']
      else
        self.proration_type = nil
      end

      if attributes.key?(:'cost_impact')
        self.cost_impact = attributes[:'cost_impact']
      else
        self.cost_impact = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @success.nil?
        invalid_properties.push('invalid value for "success", success cannot be nil.')
      end

      if @subscription_id.nil?
        invalid_properties.push('invalid value for "subscription_id", subscription_id cannot be nil.')
      end

      if @addon_product_id.nil?
        invalid_properties.push('invalid value for "addon_product_id", addon_product_id cannot be nil.')
      end

      if @old_quantity.nil?
        invalid_properties.push('invalid value for "old_quantity", old_quantity cannot be nil.')
      end

      if @new_quantity.nil?
        invalid_properties.push('invalid value for "new_quantity", new_quantity cannot be nil.')
      end

      if @quantity_delta.nil?
        invalid_properties.push('invalid value for "quantity_delta", quantity_delta cannot be nil.')
      end

      if @proration_type.nil?
        invalid_properties.push('invalid value for "proration_type", proration_type cannot be nil.')
      end

      if @cost_impact.nil?
        invalid_properties.push('invalid value for "cost_impact", cost_impact cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @success.nil?
      return false if @subscription_id.nil?
      return false if @addon_product_id.nil?
      return false if @old_quantity.nil?
      return false if @new_quantity.nil?
      return false if @quantity_delta.nil?
      return false if @proration_type.nil?
      return false if @cost_impact.nil?
      return false if @currency.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          success == o.success &&
          subscription_id == o.subscription_id &&
          addon_product_id == o.addon_product_id &&
          old_quantity == o.old_quantity &&
          new_quantity == o.new_quantity &&
          quantity_delta == o.quantity_delta &&
          proration_type == o.proration_type &&
          cost_impact == o.cost_impact &&
          currency == o.currency
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [success, subscription_id, addon_product_id, old_quantity, new_quantity, quantity_delta, proration_type, cost_impact, currency].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Solifyn.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
