=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Solifyn
  # Represents a customer subscription membership resource, containing current billing terms, plan, status, and metadata.
  class Subscription
    # The unique ID of the subscription
    attr_accessor :id

    # The status of the subscription (e.g. completed, active, trialing, past_due, canceled)
    attr_accessor :status

    # Timestamp when the subscription was created
    attr_accessor :created_at

    # Timestamp when the member joined
    attr_accessor :joined_at

    # Timestamp when the subscription was last updated
    attr_accessor :updated_at

    # The management URL for the billing/subscription
    attr_accessor :manage_url

    # The member details
    attr_accessor :member

    # The user details
    attr_accessor :user

    # Start timestamp of the current renewal period
    attr_accessor :renewal_period_start

    # End timestamp of the current renewal period
    attr_accessor :renewal_period_end

    # Whether the subscription is set to cancel at the end of the billing period
    attr_accessor :cancel_at_period_end

    # The cancel option details
    attr_accessor :cancel_option

    # The reason for cancellation
    attr_accessor :cancellation_reason

    # Timestamp when the subscription was canceled
    attr_accessor :canceled_at

    # The currency used for payments
    attr_accessor :currency

    # The company context details
    attr_accessor :company

    # The plan associated with this subscription
    attr_accessor :plan

    # The promo code applied to the subscription
    attr_accessor :promo_code

    # The product associated with the subscription
    attr_accessor :product

    # The license key associated with this subscription
    attr_accessor :license_key

    # Additional metadata for the subscription
    attr_accessor :metadata

    # Whether the payment collection is currently paused
    attr_accessor :payment_collection_paused

    # The checkout configuration ID used
    attr_accessor :checkout_configuration_id

    # The price/amount of the membership
    attr_accessor :price

    # The type of the membership plan
    attr_accessor :type

    # The business customer ID
    attr_accessor :customer_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'status' => :'status',
        :'created_at' => :'created_at',
        :'joined_at' => :'joined_at',
        :'updated_at' => :'updated_at',
        :'manage_url' => :'manage_url',
        :'member' => :'member',
        :'user' => :'user',
        :'renewal_period_start' => :'renewal_period_start',
        :'renewal_period_end' => :'renewal_period_end',
        :'cancel_at_period_end' => :'cancel_at_period_end',
        :'cancel_option' => :'cancel_option',
        :'cancellation_reason' => :'cancellation_reason',
        :'canceled_at' => :'canceled_at',
        :'currency' => :'currency',
        :'company' => :'company',
        :'plan' => :'plan',
        :'promo_code' => :'promo_code',
        :'product' => :'product',
        :'license_key' => :'license_key',
        :'metadata' => :'metadata',
        :'payment_collection_paused' => :'payment_collection_paused',
        :'checkout_configuration_id' => :'checkout_configuration_id',
        :'price' => :'price',
        :'type' => :'type',
        :'customer_id' => :'customerId'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'status' => :'String',
        :'created_at' => :'Time',
        :'joined_at' => :'Time',
        :'updated_at' => :'Time',
        :'manage_url' => :'String',
        :'member' => :'SubscriptionMemberDto',
        :'user' => :'SubscriptionUserDto',
        :'renewal_period_start' => :'Object',
        :'renewal_period_end' => :'Object',
        :'cancel_at_period_end' => :'Boolean',
        :'cancel_option' => :'Object',
        :'cancellation_reason' => :'Object',
        :'canceled_at' => :'Object',
        :'currency' => :'String',
        :'company' => :'SubscriptionCompanyDto',
        :'plan' => :'SubscriptionPlanDto',
        :'promo_code' => :'Object',
        :'product' => :'SubscriptionProductDto',
        :'license_key' => :'Object',
        :'metadata' => :'Object',
        :'payment_collection_paused' => :'Boolean',
        :'checkout_configuration_id' => :'String',
        :'price' => :'Object',
        :'type' => :'Object',
        :'customer_id' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'renewal_period_start',
        :'renewal_period_end',
        :'cancel_option',
        :'cancellation_reason',
        :'canceled_at',
        :'promo_code',
        :'license_key',
        :'price',
        :'type',
        :'customer_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Solifyn::Subscription` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Solifyn::Subscription`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'joined_at')
        self.joined_at = attributes[:'joined_at']
      else
        self.joined_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'manage_url')
        self.manage_url = attributes[:'manage_url']
      else
        self.manage_url = nil
      end

      if attributes.key?(:'member')
        self.member = attributes[:'member']
      else
        self.member = nil
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      else
        self.user = nil
      end

      if attributes.key?(:'renewal_period_start')
        self.renewal_period_start = attributes[:'renewal_period_start']
      else
        self.renewal_period_start = nil
      end

      if attributes.key?(:'renewal_period_end')
        self.renewal_period_end = attributes[:'renewal_period_end']
      else
        self.renewal_period_end = nil
      end

      if attributes.key?(:'cancel_at_period_end')
        self.cancel_at_period_end = attributes[:'cancel_at_period_end']
      else
        self.cancel_at_period_end = nil
      end

      if attributes.key?(:'cancel_option')
        self.cancel_option = attributes[:'cancel_option']
      else
        self.cancel_option = nil
      end

      if attributes.key?(:'cancellation_reason')
        self.cancellation_reason = attributes[:'cancellation_reason']
      else
        self.cancellation_reason = nil
      end

      if attributes.key?(:'canceled_at')
        self.canceled_at = attributes[:'canceled_at']
      else
        self.canceled_at = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      else
        self.company = nil
      end

      if attributes.key?(:'plan')
        self.plan = attributes[:'plan']
      else
        self.plan = nil
      end

      if attributes.key?(:'promo_code')
        self.promo_code = attributes[:'promo_code']
      else
        self.promo_code = nil
      end

      if attributes.key?(:'product')
        self.product = attributes[:'product']
      else
        self.product = nil
      end

      if attributes.key?(:'license_key')
        self.license_key = attributes[:'license_key']
      else
        self.license_key = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      else
        self.metadata = nil
      end

      if attributes.key?(:'payment_collection_paused')
        self.payment_collection_paused = attributes[:'payment_collection_paused']
      else
        self.payment_collection_paused = nil
      end

      if attributes.key?(:'checkout_configuration_id')
        self.checkout_configuration_id = attributes[:'checkout_configuration_id']
      else
        self.checkout_configuration_id = nil
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @joined_at.nil?
        invalid_properties.push('invalid value for "joined_at", joined_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @manage_url.nil?
        invalid_properties.push('invalid value for "manage_url", manage_url cannot be nil.')
      end

      if @member.nil?
        invalid_properties.push('invalid value for "member", member cannot be nil.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @cancel_at_period_end.nil?
        invalid_properties.push('invalid value for "cancel_at_period_end", cancel_at_period_end cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @company.nil?
        invalid_properties.push('invalid value for "company", company cannot be nil.')
      end

      if @plan.nil?
        invalid_properties.push('invalid value for "plan", plan cannot be nil.')
      end

      if @product.nil?
        invalid_properties.push('invalid value for "product", product cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @payment_collection_paused.nil?
        invalid_properties.push('invalid value for "payment_collection_paused", payment_collection_paused cannot be nil.')
      end

      if @checkout_configuration_id.nil?
        invalid_properties.push('invalid value for "checkout_configuration_id", checkout_configuration_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @status.nil?
      return false if @created_at.nil?
      return false if @joined_at.nil?
      return false if @updated_at.nil?
      return false if @manage_url.nil?
      return false if @member.nil?
      return false if @user.nil?
      return false if @cancel_at_period_end.nil?
      return false if @currency.nil?
      return false if @company.nil?
      return false if @plan.nil?
      return false if @product.nil?
      return false if @metadata.nil?
      return false if @payment_collection_paused.nil?
      return false if @checkout_configuration_id.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          status == o.status &&
          created_at == o.created_at &&
          joined_at == o.joined_at &&
          updated_at == o.updated_at &&
          manage_url == o.manage_url &&
          member == o.member &&
          user == o.user &&
          renewal_period_start == o.renewal_period_start &&
          renewal_period_end == o.renewal_period_end &&
          cancel_at_period_end == o.cancel_at_period_end &&
          cancel_option == o.cancel_option &&
          cancellation_reason == o.cancellation_reason &&
          canceled_at == o.canceled_at &&
          currency == o.currency &&
          company == o.company &&
          plan == o.plan &&
          promo_code == o.promo_code &&
          product == o.product &&
          license_key == o.license_key &&
          metadata == o.metadata &&
          payment_collection_paused == o.payment_collection_paused &&
          checkout_configuration_id == o.checkout_configuration_id &&
          price == o.price &&
          type == o.type &&
          customer_id == o.customer_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, status, created_at, joined_at, updated_at, manage_url, member, user, renewal_period_start, renewal_period_end, cancel_at_period_end, cancel_option, cancellation_reason, canceled_at, currency, company, plan, promo_code, product, license_key, metadata, payment_collection_paused, checkout_configuration_id, price, type, customer_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Solifyn.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
