=begin
#Solifyn API

#Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Solifyn
  class SubscriptionAction
    # Number of free days to add (used with action: add_free_days)
    attr_accessor :free_days

    # Cancellation mode (used with action: cancel)
    attr_accessor :cancellation_mode

    # Whether to void subsequent payments (used with action: pause)
    attr_accessor :void_payments

    # ID of the addon product to adjust seats for (used with action: adjust_seats)
    attr_accessor :addon_product_id

    # The new seat quantity (used with action: adjust_seats)
    attr_accessor :new_quantity

    # Proration strategy mode (used with action: adjust_seats)
    attr_accessor :proration_type

    # A unique idempotency key to prevent duplicate mutative actions for network transient retries.
    attr_accessor :idempotency_key

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'free_days' => :'free_days',
        :'cancellation_mode' => :'cancellation_mode',
        :'void_payments' => :'void_payments',
        :'addon_product_id' => :'addonProductId',
        :'new_quantity' => :'newQuantity',
        :'proration_type' => :'prorationType',
        :'idempotency_key' => :'idempotencyKey'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'free_days' => :'Float',
        :'cancellation_mode' => :'String',
        :'void_payments' => :'Boolean',
        :'addon_product_id' => :'String',
        :'new_quantity' => :'Float',
        :'proration_type' => :'String',
        :'idempotency_key' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Solifyn::SubscriptionAction` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Solifyn::SubscriptionAction`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'free_days')
        self.free_days = attributes[:'free_days']
      end

      if attributes.key?(:'cancellation_mode')
        self.cancellation_mode = attributes[:'cancellation_mode']
      end

      if attributes.key?(:'void_payments')
        self.void_payments = attributes[:'void_payments']
      end

      if attributes.key?(:'addon_product_id')
        self.addon_product_id = attributes[:'addon_product_id']
      end

      if attributes.key?(:'new_quantity')
        self.new_quantity = attributes[:'new_quantity']
      end

      if attributes.key?(:'proration_type')
        self.proration_type = attributes[:'proration_type']
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@free_days.nil? && @free_days > 3650
        invalid_properties.push('invalid value for "free_days", must be smaller than or equal to 3650.')
      end

      if !@free_days.nil? && @free_days < 1
        invalid_properties.push('invalid value for "free_days", must be greater than or equal to 1.')
      end

      if !@cancellation_mode.nil? && @cancellation_mode.to_s.length > 50
        invalid_properties.push('invalid value for "cancellation_mode", the character length must be smaller than or equal to 50.')
      end

      if !@new_quantity.nil? && @new_quantity < 0
        invalid_properties.push('invalid value for "new_quantity", must be greater than or equal to 0.')
      end

      if !@idempotency_key.nil? && @idempotency_key.to_s.length > 100
        invalid_properties.push('invalid value for "idempotency_key", the character length must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@free_days.nil? && @free_days > 3650
      return false if !@free_days.nil? && @free_days < 1
      cancellation_mode_validator = EnumAttributeValidator.new('String', ["immediate", "at_period_end"])
      return false unless cancellation_mode_validator.valid?(@cancellation_mode)
      return false if !@cancellation_mode.nil? && @cancellation_mode.to_s.length > 50
      return false if !@new_quantity.nil? && @new_quantity < 0
      proration_type_validator = EnumAttributeValidator.new('String', ["prorated_immediately", "full_immediately", "difference_immediately", "do_not_bill"])
      return false unless proration_type_validator.valid?(@proration_type)
      return false if !@idempotency_key.nil? && @idempotency_key.to_s.length > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] free_days Value to be assigned
    def free_days=(free_days)
      if free_days.nil?
        fail ArgumentError, 'free_days cannot be nil'
      end

      if free_days > 3650
        fail ArgumentError, 'invalid value for "free_days", must be smaller than or equal to 3650.'
      end

      if free_days < 1
        fail ArgumentError, 'invalid value for "free_days", must be greater than or equal to 1.'
      end

      @free_days = free_days
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cancellation_mode Object to be assigned
    def cancellation_mode=(cancellation_mode)
      validator = EnumAttributeValidator.new('String', ["immediate", "at_period_end"])
      unless validator.valid?(cancellation_mode)
        fail ArgumentError, "invalid value for \"cancellation_mode\", must be one of #{validator.allowable_values}."
      end
      @cancellation_mode = cancellation_mode
    end

    # Custom attribute writer method with validation
    # @param [Object] new_quantity Value to be assigned
    def new_quantity=(new_quantity)
      if new_quantity.nil?
        fail ArgumentError, 'new_quantity cannot be nil'
      end

      if new_quantity < 0
        fail ArgumentError, 'invalid value for "new_quantity", must be greater than or equal to 0.'
      end

      @new_quantity = new_quantity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] proration_type Object to be assigned
    def proration_type=(proration_type)
      validator = EnumAttributeValidator.new('String', ["prorated_immediately", "full_immediately", "difference_immediately", "do_not_bill"])
      unless validator.valid?(proration_type)
        fail ArgumentError, "invalid value for \"proration_type\", must be one of #{validator.allowable_values}."
      end
      @proration_type = proration_type
    end

    # Custom attribute writer method with validation
    # @param [Object] idempotency_key Value to be assigned
    def idempotency_key=(idempotency_key)
      if idempotency_key.nil?
        fail ArgumentError, 'idempotency_key cannot be nil'
      end

      if idempotency_key.to_s.length > 100
        fail ArgumentError, 'invalid value for "idempotency_key", the character length must be smaller than or equal to 100.'
      end

      @idempotency_key = idempotency_key
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          free_days == o.free_days &&
          cancellation_mode == o.cancellation_mode &&
          void_payments == o.void_payments &&
          addon_product_id == o.addon_product_id &&
          new_quantity == o.new_quantity &&
          proration_type == o.proration_type &&
          idempotency_key == o.idempotency_key
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [free_days, cancellation_mode, void_payments, addon_product_id, new_quantity, proration_type, idempotency_key].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Solifyn.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
